[versions]
# This project version
bigbone = "2.0.0-SNAPSHOT"

# 3rd party dependencies
gson = "2.10.1"
junit-jupiter = "5.10.0"
junit-platform-launcher = "1.10.0"
junit-platform-suite-engine = "1.10.0"
kluent = "1.73"
kotlin = "1.9.10"
kotlin-coroutines = "1.7.3"
mockk = "1.13.7"
okhttp = "4.11.0"
rxjava = "3.1.8"

# Gradle plugins
jacoco = "0.8.9"
dependency-analysis = "1.25.0"
detekt = "1.23.1"
versions = "0.49.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junit-platform-suite-engine" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
rxjava = { module="io.reactivex.rxjava3:rxjava", version.ref="rxjava"}
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
