build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
     - 'ProjectStatisticsReport'
     - 'ComplexityReport'
     - 'NotificationReport'

output-reports:
  active: true
  exclude:
   - 'TxtOutputReport'
   - 'HtmlOutputReport'
   - 'MdOutputReport'

comments:
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
    excludes: ['**/test/**']
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: true
    excludes: ['**/test/**', '**/sample/**']
  UndocumentedPublicFunction:
    active: false    # ***** ENABLE! *****
    excludes: ['**/test/**']
  UndocumentedPublicProperty:
    active: false    # ***** ENABLE! *****
    excludes: ['**/test/**']
    searchProtectedProperty: false

complexity:
  ComplexInterface:
    active: true
  CyclomaticComplexMethod:
    active: false   # ***** ENABLE! *****
  LabeledExpression:
    active: false   # ***** ENABLE! *****
  LongMethod:
    active: false   # ***** ENABLE! *****
  LongParameterList:
    active: false   # ***** ENABLE! *****
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: false   # ***** ENABLE! *****
    excludes: ['**/test/**']

coroutines:
  GlobalCoroutineUsage:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true

formatting:
  ClassName:
    active: true
  DiscouragedCommentLocation:
    active: true
  EnumWrapping:
    active: true
  FunctionName:
    active: true
  FunctionSignature:
    active: false   # ***** ENABLE! *****
    maxLineLength: 160
  IfElseBracing:
    active: true
  MaximumLineLength:
    active: true
    maxLineLength: 160
  NoConsecutiveComments:
    active: true
  NoEmptyFirstLineInClassBody:
    active: false   # ***** ENABLE! *****
  NoSingleLineBlockComment:
    active: true
  ParameterListWrapping:
    active: true
    maxLineLength: 160
  PropertyName:
    active: true
  StringTemplateIndent:
    active: true
  TryCatchFinallySpacing:
    active: true
  TypeArgumentListSpacing:
    active: true

naming:
  BooleanPropertyNaming:
    active: true
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 50
    excludes: ['**/test/**', '**/integrationTest/**']
  FunctionMinLength:
    active: true
  VariableMaxLength:
    active: true
  VariableMinLength:
    active: true

performance:
  CouldBeSequence:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true

potential-bugs:
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ExitOutsideMain:
    active: true


  ImplicitUnitReturnType:
    active: true
  MissingPackageDeclaration:
    active: true
    excludes: ['**/*.kts']
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true

style:
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: never
    multiLine: always
  BracesOnWhenStatements:
    active: true
    singleLine: never
    multiLine: necessary
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  DoubleNegativeLambda:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenAnnotation:
    active: true
  ForbiddenMethodCall:
    active: true
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 160
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  StringShouldBeRawString:
    active: true
    excludes: ['**/test/**', '**/integrationTest/**']     # Remove in the future
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseLet:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
