name: Build

on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]

# Cancel previous runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run build with Gradle Wrapper
        run: ./gradlew check jacocoTestReport
      - name: Codecov
        uses: codecov/codecov-action@v5
